name: banbiao_xiaoli
description: 我的记录
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.2.2
  path_provider: 2.1.4
  share_plus: 10.1.2
  lunar: ^1.7.4
  flutter_local_notifications: 17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  # ⚠️ 注意：这里一定要和你放在项目根目录的图片名字一模一样。
  # 如果你之前重命名成了 icon.jpg 就写 icon.jpg，如果是 icon.png 就写 icon.png
  image_path: "icon.jpg" 